# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

SignalConfigs:
  # Video decode
  # Default decode
  - SigId: "0x0001"
    Category: "0x03"
    Name: "URM_SIG_VIDEO_DECODE"
    Enable: true
    TargetsEnabled: ["qcs8300", "qcs8275", "sa7255p"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_LITTLE_ALL_CORES", Values: [1200000]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_BIG_ALL_CORES", Values: [1200000]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_PLUS_ALL_CORES", Values: [1200000]}

  # Video decode
  # Decode 5-20 concurrent sessions
  - SigId: "0x0001"
    Category: "0x03"
    Type: 5
    Name: "URM_SIG_VIDEO_DECODE"
    Enable: true
    TargetsEnabled: ["qcs8300", "qcs8275", "sa7255p"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_LITTLE_ALL_CORES", Values: [1500000]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_BIG_ALL_CORES", Values: [1500000]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_PLUS_ALL_CORES", Values: [1500000]}

  # Video decode
  # Decode 20+ concurrent sessions
  - SigId: "0x0001"
    Category: "0x03"
    Type: 20
    Name: "URM_SIG_VIDEO_DECODE"
    Enable: true
    TargetsEnabled: ["qcs8300", "qcs8275", "sa7255p"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}

  # Camera preview
  # Default preview - 30fps
  - SigId: "0x0002"
    Category: "0x03"
    Name: "URM_SIG_CAMERA_PREVIEW"
    Enable: true
    TargetsEnabled: ["qcs8300", "qcs8275", "sa7255p"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_LITTLE_ALL_CORES", Values: [1200000]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_BIG_ALL_CORES", Values: [1200000]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_PLUS_ALL_CORES", Values: [1200000]}

  # camera encode
  # Default encode - 30fps
  - SigId: "0x0003"
    Category: "0x03"
    Name: "URM_SIG_CAMERA_ENCODE"
    Enable: true
    TargetsEnabled: ["qcs8300", "qcs8275", "sa7255p"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_LITTLE_ALL_CORES", Values: [1200000]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_BIG_ALL_CORES", Values: [1200000]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_PLUS_ALL_CORES", Values: [1200000]}

  # camera encode multi-stream
  # encode (0-12 streams)
  - SigId: "0x0004"
    Category: "0x03"
    Name: URM_SIG_CAMERA_ENCODE_MULTI_STREAMS
    Enable: true
    TargetsEnabled: ["qcs8300", "qcs8275", "sa7255p"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_LITTLE_ALL_CORES", Values: [1500000]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_BIG_ALL_CORES", Values: [1500000]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_PLUS_ALL_CORES", Values: [1500000]}

  # camera encode multi-stream
  # encode (12+ streams)
  - SigId: "0x0004"
    Category: "0x03"
    Type: 12
    Name: URM_SIG_CAMERA_ENCODE_MULTI_STREAMS
    Enable: true
    TargetsEnabled: ["qcs8300", "qcs8275", "sa7255p"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4,5,6,7]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}

  # camera open tunings
  # CPU cluster Silver(Little) Min Freq 1958400 KHz, Max Freq 1958400 KHz
  # CPU cluster Gold(Big) Min Freq 2112000 KHz, Max Freq 2112000 KHz
  # CPU cluster Gold_plus(Prime) Min Freq 2361600 KHz, Max Freq 2361600 KHz
  - SigId: "0x1337"
    Category: "0xea"
    Name: "CAMERA_OPEN"
    Enable: true
    TargetsEnabled: ["qcs8300", "qcs8275", "sa7255p"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "0x00040000", ResInfo: "0x00000000", Values: [1958400]}
      - {ResCode: "0x00040001", ResInfo: "0x00000000", Values: [1958400]}
      - {ResCode: "0x00040000", ResInfo: "0x00000100", Values: [2112000]}
      - {ResCode: "0x00040001", ResInfo: "0x00000100", Values: [2112000]}
      - {ResCode: "0x00040000", ResInfo: "0x00000200", Values: [2361600]}
      - {ResCode: "0x00040001", ResInfo: "0x00000200", Values: [2361600]}

  # camera close tunings
  # CPU cluster Silver(Little) Min Freq 1958400 KHz, Max Freq 1958400 KHz
  # CPU cluster Gold(Big) Min Freq 2112000 KHz, Max Freq 2112000 KHz
  # CPU cluster Gold_plus(Prime) Min Freq 2361600 KHz, Max Freq 2361600 KHz
  - SigId: "0x1338"
    Category: "0xea"
    Name: "CAMERA_CLOSE"
    Enable: true
    TargetsEnabled: ["qcs8300", "qcs8275", "sa7255p"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "0x00040000", ResInfo: "0x00000000", Values: [1958400]}
      - {ResCode: "0x00040001", ResInfo: "0x00000000", Values: [1958400]}
      - {ResCode: "0x00040000", ResInfo: "0x00000100", Values: [2112000]}
      - {ResCode: "0x00040001", ResInfo: "0x00000100", Values: [2112000]}
      - {ResCode: "0x00040000", ResInfo: "0x00000200", Values: [2361600]}
      - {ResCode: "0x00040001", ResInfo: "0x00000200", Values: [2361600]}
