# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

SignalConfigs:
  # Video decode
  # Default decode 30 fps
  - SigId: "0x0001"
    Category: "0x03"
    Name: "URM_SIG_VIDEO_DECODE"
    Enable: true
    TargetsEnabled: ["glymur", "glymur-crd"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3,4,5]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 0,1,2,3,4,5]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 6,7,8,9,10,11]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MIN", Values: [0]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MAX", Values: [153]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_LITTLE_ALL_CORES", Values: [806400]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_BIG_ALL_CORES", Values: [940800]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_PLUS_ALL_CORES", Values: [940800]}

  # Video decode
  # Decode 5-20 concurrent sessions
  - SigId: "0x0001"
    Type: 5
    Name: "URM_SIG_VIDEO_DECODE"
    Enable: true
    TargetsEnabled: ["glymur", "glymur-crd"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3,4,5]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 0,1,2,3,4,5]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 6,7,8,9,10,11]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MIN", Values: [0]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MAX", Values: [307]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_LITTLE_ALL_CORES", Values: [940800]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_BIG_ALL_CORES", Values: [1228800]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_PLUS_ALL_CORES", Values: [1228800]}

  # Video decode
  # Decode 20+ concurrent sessions
  - SigId: "0x0001"
    Type: 20
    Name: "URM_SIG_VIDEO_DECODE"
    Enable: true
    TargetsEnabled: ["glymur", "glymur-crd"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3,4,5]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 0,1,2,3,4,5]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 6,7,8,9,10,11]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}

  # Camera preview
  # Default preview - 30fps
  - SigId: "0x0002"
    Category: "0x03"
    Name: "URM_SIG_CAMERA_PREVIEW"
    Enable: true
    TargetsEnabled: ["glymur", "glymur-crd"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3,4,5]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 0,1,2,3,4,5]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 6,7,8,9,10,11]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MIN", Values: [0]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MAX", Values: [153]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_LITTLE_ALL_CORES", Values: [940800]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_BIG_ALL_CORES", Values: [940800]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_PLUS_ALL_CORES", Values: [940800]}

  # camera encode
  # Default encode - 30fps
  - SigId: "0x0003"
    Category: "0x03"
    Name: "URM_SIG_CAMERA_ENCODE"
    Enable: true
    TargetsEnabled: ["glymur", "glymur-crd"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3,4,5]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 0,1,2,3,4,5]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 6,7,8,9,10,11]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MIN", Values: [0]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MAX", Values: [153]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_LITTLE_ALL_CORES", Values: [806400]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_BIG_ALL_CORES", Values: [940800]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_PLUS_ALL_CORES", Values: [940800]}

  # Camera encode
  # Default encode - 4k 30fps case
  - SigId: "0x0003"
    Category: "0x03"
    Name: "URM_SIG_CAMERA_ENCODE"
    Enable: true
    TargetsEnabled: ["glymur", "glymur-crd"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    ExtraAttrs:
      - Fps: 30
      - Height: 2160
      - Width: 3840
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3,4,5]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 0,1,2,3,4,5]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 6,7,8,9,10,11]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MIN", Values: [0]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MAX", Values: [410]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_LITTLE_ALL_CORES", Values: [806400]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_BIG_ALL_CORES", Values: [940800]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_PLUS_ALL_CORES", Values: [940800]}

  # camera encode multi-stream
  # encode (0-12 streams) [sigtype : 0 for normal load (<12 stream)]
  - SigId: "0x0004"
    Category: "0x03"
    SigType: 0
    Name: "URM_SIG_CAMERA_ENCODE_MULTI_STREAMS"
    Enable: true
    TargetsEnabled: ["glymur", "glymur-crd"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3,4,5]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 0,1,2,3,4,5]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 6,7,8,9,10,11]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MIN", Values: [0]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MAX", Values: [410]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_LITTLE_ALL_CORES", Values: [806400]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_BIG_ALL_CORES", Values: [940800]}
      - {ResCode: "RES_SCALE_MAX_FREQ", ResInfo: "CLUSTER_PLUS_ALL_CORES", Values: [940800]}

  # camera encode multi-stream
  # encode (12+ streams) [sigtype : 13 for high load (>12 stream)]
  - SigId: "0x0004"
    Category: "0x03"
    SigType: 13
    Name: "URM_SIG_CAMERA_ENCODE_MULTI_STREAMS"
    Enable: true
    TargetsEnabled: ["glymur", "glymur-crd"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3,4,5]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 0,1,2,3,4,5]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 6,7,8,9,10,11]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MIN", Values: [0]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MAX", Values: [716]}
